"""empty message

Revision ID: 936d865110ce
Revises: b3d58a6f15b6
Create Date: 2024-05-15 19:06:02.986153

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '936d865110ce'
down_revision = 'b3d58a6f15b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=80), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('username')

    # ### end Alembic commands ###
